### ISSUE TITLE
Make error？

### ISSUE THREAD

**Issue by zmf2022** [hipudding/llama.cpp#3]
llama.cpp/ggml-impl.h:283:27: error: implicit declaration of function ‘vld1q_s16_x2’; did you mean ‘vld1q_s16’? [-Werror=implicit-function-declaration]
 #define ggml_vld1q_s16_x2 vld1q_s16_x2

llama.cpp/ggml-quants.c:4780:41: note: in expansion of macro ‘ggml_vld1q_s16_x2’
         const ggml_int16x8x2_t q8sums = ggml_vld1q_s16_x2(y[i].bsums);
                                         ^~~~~~~~~~~~~~~~~
llama.cpp/ggml-impl.h:283:27: error: invalid initializer
 #define ggml_vld1q_s16_x2 vld1q_s16_x2

**Comment by hipudding** [comment]
This PR is still under progress, please wait for release.

**Comment by hipudding** [comment]
Npu support has been merged. Please compile it with -DGGML_CANN=on.
